# Generated by Django 6.0.6 on 2026-06-10 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='roll',
        ),
    ]
